import Head from 'next/head'
import {BsFillMoonStarsFill} from "react-icons/bs";
import {AiFillTwitterCircle, AiFillLinkedin, AiFillYoutube} from "react-icons/ai";
import Image from 'next/image';
import deved from '../public/dev-ed-wave.png';
import design from '../public/design.png';
import code from '../public/code.png';
import consulting from '../public/consulting.png';
import web1 from '../public/web1.png';
import web2 from '../public/web2.png';
import web3 from '../public/web3.png';
import web4 from '../public/web4.png';
import web5 from '../public/web5.png';
import web6 from '../public/web6.png';
import {useState} from 'react';
export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? 'dark' : ''}>
      <Head>
        <title>Web Devloper Portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900'>
        <section className='min-h-screen'>
            <nav className='py-10 mb-12 flex justify-between'>
              <h1 className='text-xl font-burtons dark:text-white'>WebDeveloper</h1>
              <ul className='flex items-center'>
                <li><BsFillMoonStarsFill 
                  onClick={() => {
                    setDarkMode(!darkMode)
                  }}
                  className='cursor-pointer text-xl dark:text-white'

                  />
                  </li>
                <li><a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8'  href='#'>Resume</a></li>
              </ul>
            </nav>
            <div className='text-center p-10'>
              <h2 className='text-5xl py-2 text-teal-600 font-medium md:text-6xl'>Website Developer</h2>
              <h3 className='text-2xl py-2 md:text-3xl dark:text-white' >Developer and Designer.</h3>
              <p className='text-md py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto dark:text-white'>Creating web pages using Notepad, or a similar text editor, is a task that 
              any experienced web developer should be able to complete.</p>
            </div>
            <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-white'>
              <AiFillTwitterCircle/>
              <AiFillLinkedin/>
              <AiFillYoutube/>
            </div>
            <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:w-96 md:h-96'>
              <Image src={deved} layout="fill" objectFit='cover'/>
            </div>
        </section>
        {/* section path2 */}
        <section>
          <div>
            <h3 className='text-3xl py-1 dark:text-white'>Services I offer</h3>
            <p className='text-mb py-2 leading-8 text-gray-800 dark:text-white'>
                Hire a web developer by searching social networking sites,
                <span className='text-teal-500'> agencies </span> and
                as a <span className='text-teal-500'>web developer</span> freelance specilizes in remote work developer!
            </p>
            <p className='text-mb py-2 leading-8 text-gray-800 dark:text-white'>
              I offer from a wide range of services, including teacing, programming
              and training newbie.
            </p>
          </div>
          <div className='lg:flex gap-10'>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white'>
              <div className='flex justify-center'>
              <Image src={design} width={100} height={100} />
              </div>
              <h3 className='text-lg font-medium pt-8 pb-2'>Beautiful Design</h3>
              <p className='py-2'>
                Created elegent design suited for your need 
                following core design theory.
              </p>
              <h4 className='py-4 text-teal-600'>Design tools I use:</h4>
              <p className='text-gray-800 py-1'>Photoshop</p>
              <p className='text-gray-800 py-1'>Figma</p>
              <p className='text-gray-800 py-1'>Canva</p>
              <p className='text-gray-800 py-1'>Power Director</p>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white'>
              <div className='flex justify-center'>
              <Image src={code} width={100} height={100} />
              </div>
              <h3 className='text-lg font-medium pt-8 pb-2'>Beautiful Design</h3>
              <p className='py-2'>
                Created elegent design suited for your need 
                following core design theory.
              </p>
              <h4 className='py-4 text-teal-600'>Design tools I use:</h4>
              <p className='text-gray-800 py-1'>Photoshop</p>
              <p className='text-gray-800 py-1'>Figma</p>
              <p className='text-gray-800 py-1'>Canva</p>
              <p className='text-gray-800 py-1'>Power Director</p>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white'>
              <div className='flex justify-center'>
              <Image src={consulting} width={100} height={100} />
              </div>
              <h3 className='text-lg font-medium pt-8 pb-2'>Beautiful Design</h3>
              <p className='py-2'>
                Created elegent design suited for your need 
                following core design theory.
              </p>
              <h4 className='py-4 text-teal-600'>Design tools I use:</h4>
              <p className='text-gray-800 py-1'>Photoshop</p>
              <p className='text-gray-800 py-1'>Figma</p>
              <p className='text-gray-800 py-1'>Canva</p>
              <p className='text-gray-800 py-1'>Power Director</p>
            </div>
          </div>
        </section>
        {/* part3 */}
        <section>
          <div>
            <h3 className='text-3xl py-1 dark:text-white'>Portofolio</h3>
            <p className='text-mb py-2 leading-8 text-gray-800 dark:text-white'>
                Hire a web developer by searching social networking sites,
                <span className='text-teal-500'> agencies </span> and
                as a <span className='text-teal-500'>web developer</span> freelance specilizes in remote work developer!
            </p>
            <p className='text-mb py-2 leading-8 text-gray-800 dark:text-white'>
              I offer from a wide range of services, including teacing, programming
              and training newbie.
            </p>
          </div>
          <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
            <div className='basis-1/3 flex-1'>
              <Image src={web1} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive' />
              </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web2} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive' />
              </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web3} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive' />
              </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web4} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive' />
              </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web5} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive' />
              </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web6} className='rounded-lg object-cover' width={'100%'} height={'100%'} layout='responsive' />
              </div>
          </div>
        </section>
        <footer className="text-gray-600 body-font">
          <div className="container px-5 py-8 mx-auto flex items-center sm:flex-row flex-col">
            <p className="text-sm text-gray-500 sm:ml-4 sm:pl-4 sm:border-l-2 sm:border-gray-200 sm:py-2 sm:mt-0 mt-4 dark:text-white">© 2022 WebDeveloper —
              <a href="#" className="text-gray-600 ml-1 dark:text-white" rel="noopener noreferrer" target="_blank">@web-developer</a>
            </p>
            <span className="inline-flex sm:ml-auto sm:mt-0 mt-4 justify-center sm:justify-start">
              <a className="text-gray-500 dark:text-white">
                <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" className="w-5 h-5" viewBox="0 0 24 24">
                  <path d="M18 2h-3a5 5 0 00-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 011-1h3z"></path>
                </svg>
              </a>
              <a className="ml-3 text-gray-500 dark:text-white">
                <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" className="w-5 h-5" viewBox="0 0 24 24">
                  <path d="M23 3a10.9 10.9 0 01-3.14 1.53 4.48 4.48 0 00-7.86 3v1A10.66 10.66 0 013 4s-4 9 5 13a11.64 11.64 0 01-7 2c9 5 20 0 20-11.5a4.5 4.5 0 00-.08-.83A7.72 7.72 0 0023 3z"></path>
                </svg>
              </a>
              <a className="ml-3 text-gray-500 dark:text-white">
                <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" className="w-5 h-5" viewBox="0 0 24 24">
                  <rect width="20" height="20" x="2" y="2" rx="5" ry="5"></rect>
                  <path d="M16 11.37A4 4 0 1112.63 8 4 4 0 0116 11.37zm1.5-4.87h.01"></path>
                </svg>
              </a>
              <a className="ml-3 text-gray-500 dark:text-white">
                <svg fill="currentColor" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="0" className="w-5 h-5" viewBox="0 0 24 24">
                  <path stroke="none" d="M16 8a6 6 0 016 6v7h-4v-7a2 2 0 00-2-2 2 2 0 00-2 2v7h-4v-7a6 6 0 016-6zM2 9h4v12H2z"></path>
                  <circle cx="4" cy="4" r="2" stroke="none"></circle>
                </svg>
              </a>
            </span>
          </div>
        </footer>
      </main>

      
    </div>
  )
}
